### ISSUE TITLE
Google.Apis.Oauth2.v2 1.36 is required

### ISSUE THREAD

**Issue by GillesMart** [runerasmussen/google-photos-upload#1]
Hello,
It seems that the latest version of Google.Apis.Oauth2.v2 is required, so as to avoid this bug:
https://github.com/googleapis/google-api-dotnet-client/issues/1301

I think this should be indicated in the .csproj file.

Best regards.

**Comment by runerasmussen** [comment]
Thanks for reporting the issue. 
The lastest version of the Google.Apis.Auth has been added to the solution in commit a1d8e2eb267aeef3ad7d9436f99243ffdd7307ff and resolves the issue.
On official Release will be coming at some point soon, but for now you can take the latest source code from Master branch. Please reopen the issue if it still persists for you @GillesMart.
