### ISSUE TITLE
Error 500 when interacting with Google Photos server

### ISSUE THREAD

**Issue by GillesMart** [runerasmussen/google-photos-upload#2]
Hi,
I get an error 500 after fetching the list of albums (there's only one called "toto"), or after trying to upload 2 images from a test directory:

> INFO
>INFO Fetching albums...
>INFO > toto
>Unhandled Exception: Google.GoogleApiException: Google.Apis.Requests.RequestError Internal error >encountered. [500]
>Errors [Message[Internal error encountered.] Location[ - ] Reason[backendError]
>Domain[global]
>]
>
>at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response) in C:\Apiary\2018-10-17.13-21-41\Src\Support\Google.Apis\Requests\ClientServiceRequest.cs:line 192
>at Google.Apis.Requests.ClientServiceRequest`1.Execute() in C:\Apiary\2018-10-17.13-21-41\Src\Support\Google.Apis\Requests\ClientServiceRequest.cs:line 116
>at google_photos_upload.Model.MyAlbum.ListAlbums(PhotosLibraryService service, ILogger logger) in d:\download\google-photos-upload\Model\MyAlbum.cs:line 54
>at google_photos_upload.UploadHandler.ListAlbums() in d:\download\google-photos-upload\UploadHandler.cs:line 29
>at google_photos_upload.Program.Main(String[] args) in d:\download\google-photos-upload\Program.cs:line 62 

or:

>What folder do you want to upload?
>d:\test
>
>Uploading Album: test
>INFO Uploading IMG_20181208_180546.jpg
>INFO Uploading IMG_20181208_181924.jpg
>
>Unhandled Exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
>Internal error encountered. [500]Errors [
>        Message[Internal error encountered.] Location[ - ] Reason[backendError]
>Domain[global]
>]
>
>   at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response) in C:\Apiary\2018-10-17.13-21-41\Src\Support\Google.Apis\Requests\ClientServiceRequest.cs:line 192
>   at Google.Apis.Requests.ClientServiceRequest`1.Execute() in C:\Apiary\2018-10-17.13-21-41\Src\Support\Google.Apis\Requests\ClientServiceRequest.cs:line 116
>   at google_photos_upload.Model.MyAlbum.GetAlbum() in d:\download\google-photos-upload\Model\MyAlbum.cs:line 209
>   at google_photos_upload.Model.MyAlbum.UploadAlbum() in d:\download\google-photos-upload\Model\MyAlbum.cs:line 103
>   at google_photos_upload.UploadHandler.ProcessAlbumDirectory(String path) in d:\download\google-photos-upload\UploadHandler.cs:line 86
>   at google_photos_upload.UploadHandler.ProcessAlbumDirectory() in d:\download\google-photos-upload\UploadHandler.cs:line 71
>   at google_photos_upload.Program.Main(String[] args) in d:\download\google-photos-upload\Program.cs:line 65

It's a very generic error, and I don't know what to try from this point to solve the problem.
Best regards.

**Comment by runerasmussen** [comment]
It is unfortunately not possible for me to reproduce either of the two variances of the reported issue.
The error code 500 indicates a Google internal server error (assuming this is an HTTP code) at the time it was experienced.
It may be that I have resolved the issue indirectly when upgrading Google.Apis.Auth Nuget package to resolve the other issue  reported on authentication (issue #1).
@GillesMart do you still experience the issue using the latest Master branch source code? Please can you provide more details and ideally provide a link to where I can get the test images you have been using.
It will close the issue for now until proven otherwise.
