### ISSUE TITLE
Command Line parameters

### ISSUE THREAD

**Issue by praetor100** [runerasmussen/google-photos-upload#4]
Is there a way to use Command Line parameters?

greetings
praetor

**Comment by runerasmussen** [comment]
Hello @praetor100 

Currently the tool does not support Command Line parameters, but it is in the backlog to leverage Mono.Options to make this possible at some point.
Given this is a hobby project managed single-person I cannot currently say by when it will be implemented, but it's great to know there is an interest in this feature.

The tool already has an option to import sub directories from a given master directory, perhaps you will find this useful in the meanwhile :-)

**Comment by praetor100** [comment]
Thanks for your quick reply.
I would like to explain why a commandline option would be great: I occasionally write as a hobby script extensions (VBScript) for the program "Fix-Foto]" (https://www.j-k-s.com, https://sites.google.com/site/fixfotohilfe/) for photo editing. Your program could be well integrated there.

greetings
Andreas

**Comment by runerasmussen** [comment]
@praetor100 thanks for providing reasoning for the enhancement request. At this point in time I cannot say if/by when this feature will be added, but it is a feature I already had in the backlog and agree will be useful in some scenarios.

**Comment by runerasmussen** [comment]
Hello @praetor100 
I'm pleased to share that I have worked on this enhancement request for passing command parameters.
At your convenience, please can you give it a try and provide feedback.

It is not yet available under Releases as it's not yet merged into the Master branch. I have attached here the [portable.zip](https://github.com/runerasmussen/google-photos-upload/files/3033443/portable.zip) which requires dotnet core to be installed on your machine, as the exe version is too big to attach here.

You can execute the tool this way to see the help:
dotnet google-photos-upload.dll -h

**Comment by praetor100** [comment]
Hello Rune
Thanks for the trial. I will try that as soon as possible.
Best regards
Andreas

Am Di., 2. Apr. 2019 um 12:23 Uhr schrieb Rune Rasmussen <
notifications@github.com>:

**Comment by praetor100** [comment]
Hello Rune,

I have tested now. Everything works fine. However, if images do not have
Exif data, it takes a long time. Is there a longer timeout installed?
There will surely be an exe file?

Best regards
Andreas

Am Di., 2. Apr. 2019 um 21:54 Uhr schrieb praetor <praetor100@gmail.com>:

**Comment by runerasmussen** [comment]
Good evening @praetor100

Great to hear the command parameters works well for you also. 
The functionality to read EXIF data should not have unchanged really. Do you also see the long timeout for the previous 0.6 release?

**Comment by praetor100** [comment]
Yes, the long time out has always been there.

Rune Rasmussen <notifications@github.com> schrieb am Do., 4. Apr. 2019,
22:55:

**Comment by runerasmussen** [comment]
I have tried the replicate the issue with the long timeout, but even with or without EXIF data seem to work ok for me. It might be an issue with the library used to read the EXIF data. Please can you raise a separate issue for this with further details and preferably sample images attached?

Alpha Release 0.7 is now available incl. a Windows 10 exe version:
https://github.com/runerasmussen/google-photos-upload/releases/tag/v0.7-alpha

I will close this issue, given the objective of the request has been met.
