### ISSUE TITLE
request: also pictures without EXIF block

### ISSUE THREAD

**Issue by praetor100** [runerasmussen/google-photos-upload#5]
The tool does not accept images at this time without the "Date Taken Original" EXIF property. It would be good if optional images without EXIF block would accept or with EXIF block, but without property "Date Taken Original".
Google photos automatically assigns the current date to such images. In many cases this is a meaningful behavior.

Greetings
Andreas

**Comment by runerasmussen** [comment]
@praetor100, good news: A feature has been added to allow images without EXIF Date Taken Original to be uploaded. This can be controlled in App.config and the default value is "true" which will allow these images/videos to be uploaded.

See 0.6 Alpha Release:
https://github.com/runerasmussen/google-photos-upload/releases/tag/0.6-alpha

**Comment by praetor100** [comment]
This works very well. Many Thanks.

**Comment by runerasmussen** [comment]
Excellent, I’m closing the issue.
