### ISSUE TITLE
Comparison with prior art

### ISSUE THREAD

**Issue by dandv** [runerasmussen/google-photos-upload#6]
Hi, thanks for publishing this! I'm curious how it compares with @nmrshll's [gphotos-uploader-cli](https://github.com/nmrshll/gphotos-uploader-cli).

**Comment by runerasmussen** [comment]
Hi @dandv, I believe there are multiple tools related to Google Photos available on Github. I have not evaluated the tool you are referring to.
The specific feature that my tool focuses on is to ensure an Album is created in Google Photos for each Folder that has been uploaded. This preserves history and image organization that some people find useful.
You are free to do an in-depth comparison and share the result here. For now I will close the issue.

**Comment by nmrshll** [comment]
Hi @dandy,
I'm the creator of the other tool you mentioned. I would say they are
pretty similar. If anything I don't know how this tool performs but still
mine has a few rough edges (there's a little bug in the feature that's
supposed to create albums for each folder, metadata is not conserved
properly at the moment, among other things). There's people helping me make
it better at the moment.

One big difference: mine doesn't work on windows, so if you use windows i'd
recommend trying @runerasmussen's one.

Hope that helps a bit

Le ven. 22 mars 2019 à 11:50, Rune Rasmussen <notifications@github.com> a
écrit :

**Comment by dandy** [comment]
Hi I think you mistakenly tagged me(@dandy) instead of @dandv 
/BR

**Comment by nmrshll** [comment]
ah yes sorry
