### ISSUE TITLE
EXIF block is not recognized

### ISSUE THREAD

**Issue by praetor100** [runerasmussen/google-photos-upload#7]
For some pictures the EXIF block is not recognized correctly. The sample image contains a valid EXIF block and an image description has been added. When uploading comes the message that there is no EXIF block. The image description will also be unavailable on Google Photos.

![IMG_20190509_201412](https://user-images.githubusercontent.com/11509342/57584480-0363a580-74dc-11e9-816a-f075688b62b4.jpg)

**Comment by runerasmussen** [comment]
Hi @praetor100.

Thank you for reporting this. It looks like there are two items here:

**Item 1: EXIF Description from Image is expected to be used as Description in Google Photos**
The file name (without extension) is currently being used as the Description for the media item in Google Photos. I agree with your point that if there is a Description in the EXIF data it should be used.
I suggest to use the following metadata in this prioritized order for the Description field value (first value that is present will be used):
1) EXIF Title value
2) EXIF Description value
3) File name without extension

Thoughts?



**Item 2: EXIF block not being read on the reported image.**
The tool is using an third-party library to read the EXIF data and this library is failing with an Exception when trying to read EXIF data (no specific field).
This looks to be a known issue, that the owner of this library is working on (also open source, so can't comment on when it will be fixed):
https://github.com/oozcitak/exiflibrary/issues/60

Failure message is: "Unknown property type."
Stack trace:
"   at ExifLibrary.ExifPropertyFactory.Get(UInt16 tag, UInt16 type, UInt32 count, Byte[] value, ByteOrder byteOrder, IFD ifd, Encoding encoding)\r\n   at ExifLibrary.JPEGFile.ReadExifAPP1()\r\n   at ExifLibrary.JPEGFile..ctor(Stream stream, Encoding encoding)\r\n   at ExifLibrary.ImageFile.FromStream(Stream stream, Encoding encoding)\r\n   at ExifLibrary.ImageFile.FromFile(String filename, Encoding encoding)\r\n   at google_photos_upload.Model.MyImage.get_DateImageWasTaken() in C:\\Users\\rune.rasmussen\\source\\repos\\google-photos-upload\\google-photos-upload\\google-photos-upload\\Model\\MyImage.cs:line 107"

Plan for fixing this issue:
0) Wait for issue to get resolved in EXIF Library (I have subscribed to notifications for the issue 60 found)
1) Log the exception message, so the end user can see read the failure and raise an issue with better details.
2) Replace ExifLibrary (https://github.com/devedse/exiflibrary) with ExifLibNet (original forked libary found at https://www.nuget.org/packages/ExifLibNet)
3) Verify solution works

**Comment by runerasmussen** [comment]
Reg: **Item 2: EXIF block not being read on the reported image.**
I have found another library to read EXIF data, that seem to be more stable, have more features and is well supported: [ImageSharp](https://github.com/SixLabors/ImageSharp)
The work to verify if this library will work has begun.

@praetor100, please comment on Item 1

**Comment by praetor100** [comment]
to Item 1:
There are several metadata for describing the image content:
- exif: imagedescription
- iptc: caption-abstract
- iptc: headline
If an image is uploaded to Google Photos (for example, through the Googel website), the mediadata "caption-abstract" will be used with priority. I think that's appropriate.

to Item 2:
So far, I have not understood why you have to actively determine with your program, which information Google Photo uses as a picture description. I thought Google Photo automatically uses the image description when a uploaded image contains a description. Am I mistaken?
If you program in C ++, maybe this library is an option ?: http://owl.phy.queensu.ca/~phil/cpp_exiftool/

Greetings
Andreas

**Comment by runerasmussen** [comment]
@praetor100, some good news:

The new library ImageSharp works well to read EXIF data and I have resolved the reported 2 issues from this thread.
Description value for Google Photos will be derived in this order:
1) EXIF ImageDescription
2) Filename without file extension

I have taken the liberty to add the image file from your first post in this file and added it to the source code repository test data folder. I assume this is okay as it is already available here on GitHub as public domain data. If the image should be removed please let me know.

Release 0.11 is now available:
https://github.com/runerasmussen/google-photos-upload/releases/tag/v0.11-alpha


A list of EXIF tags can be found here:
https://sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html

Reason why EXIF data is relevant;
Google Photos has a single field to hold the Description value per Photo. This field is automatically set when you manually upload via the Google Photos website. The tools uses the Google Photos Public API which require us to set this value (Google does not derive it, at least that's what it looks like to me based on multiple tests - the official documentation is lacking).

Example after upload:
![image](https://user-images.githubusercontent.com/40182284/58752589-e2c2b600-84b1-11e9-9bb8-a4ec6dd71447.png)

I have closed the Issue. Please reopen with comments if you believe the issue still exists.
