### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by praetor100** [runerasmussen/google-photos-upload#8]
I suggest to attach a short description of the operation and the program parameters to the program package (TXT).

greetings
Andreas

**Comment by runerasmussen** [comment]
@praetor100, thanks for suggesting this. I do see your point, that users currently can only find out what parameters can be passed by running the "-h" parameter.
I can extract out the User Guide instructions into a separate file and include details on the parameters that can be passed so it is easier for end users to see what options there are without having to actually execute the tool. This will be stored in a .md file to stay within best practice standard for Github.

Thoughts?

**Comment by praetor100** [comment]
This is a good approach and makes it easier for the user to understand the function. But I personally do not know any file type .md, I would search for .txt, or for .inf. Who uses the program is probably not a programmer and does not know what is common on GitHub.

**Comment by praetor100** [comment]
The picture description is now correctly taken into account when uploading. That's great! The fact that the information is coming from
1. EXIF ImageDescription
2. Filename without file extension

should be considered in the readme file.
A user might otherwise get the idea of using IPTC metadata.

**Comment by runerasmussen** [comment]
@praetor100, did you close this item by mistake, as it is not yet resolved? You may have meant to close #7  ???

**Comment by praetor100** [comment]
Sorry, that was a mistake. I did not want to close this item.

**Comment by runerasmussen** [comment]
@praetor100, a User Guide has been created inside a temporary code branch on GitHub. Please take a look:
https://github.com/runerasmussen/google-photos-upload/blob/development/userguide/USER_GUIDE.md

I plan to merge it into Master branch within the next week or so. The permanent link (once released) will be:
https://github.com/runerasmussen/google-photos-upload/blob/master/USER_GUIDE.md

**Comment by praetor100** [comment]
Hello Rune,
the text is very good. My two cents:

to "Supported file types: mov, avi, jpg, jpeg, gif. Ignored file types:
txt, thm"
In fact, all other file types are not supported.

The correct parameter for calling the help is -h or -help (with hyphens).

The manual should be attached as readme.txt to the package.

Best regards
Andreas

Am Mo., 10. Juni 2019 um 17:27 Uhr schrieb Rune Rasmussen <
notifications@github.com>:

**Comment by runerasmussen** [comment]
Hello @praetor100,

Thank you for your feedback.
I have made the following updates and it is now live in master branch:
* Reworded text on file types to make it more explicit why some are ignored.
* Parameters are now prepended with a hyphen in the table
* ReadMe.txt added with a link to the online User Guide. It does not contain the user guide itself, as txt does not support the required formatting, and having an online user guide gives more flexibility.
* A few minor heading/content updates

I believe hereby the request has been fulfilled, and the issue has therefore been closed.

https://github.com/runerasmussen/google-photos-upload/blob/master/USER_GUIDE.md

Have a great day!

Kind regards,
Rune
