### ISSUE TITLE
Upload aborts

### ISSUE THREAD

**Issue by praetor100** [runerasmussen/google-photos-upload#9]
Hi,
I use Alpha Release 11. Unfortunately, the upload stops at different folders again and again. Enclosed the logs of the last attempt. What could that be?
[log.zip](https://github.com/runerasmussen/google-photos-upload/files/3587424/log.zip)

Best regards
praetor

**Comment by runerasmussen** [comment]
Hi @praetor100, Thanks for reporting this issue.
I have not experienced the issue myself, but you may have used large volume of data.
Based on the log file you provided it looks like it's a constraint the Google Photos API when uploading.
Possible reasons can be:
a) The file being uploaded is more than 50MB.
b) The number of files being uploaded is very large (1000+)

Can you comment on which of these it may be?

Kind regards,
Rune

**Comment by runerasmussen** [comment]
Hi @praetor100, until now I have not been succesful in duplicating the issue. However while investigating this I have found an enhancement that can be done to this area of the code and am also adding in further logging so we can get better insight into the issue. 
I will share the new version here in this thread soon, hoping you don't mind trying it out.

**Comment by runerasmussen** [comment]
Hi @praetor100 
Alpha Release 12 is now available for you.
Please use it to capture further log statements that can help us identify the root cause, and share the log file here for my analysis.
https://github.com/runerasmussen/google-photos-upload/releases/tag/v0.12-alpha

**Comment by praetor100** [comment]
Hi Rune,
I tried Alpha Release 12. There was no error, the directory was completely uploaded. I will keep watching.
